### ISSUE TITLE
3 tests fail on ECL's bytecode compiler

### ISSUE THREAD

**Issue by avodonosov** [trivial-garbage/trivial-garbage#7]
TRIVIAL-GARBAGE-TESTS::FINALIZERS.1, TRIVIAL-GARBAGE-TESTS::FINALIZERS.3, TRIVIAL-GARBAGE-TESTS::FINALIZERS.5.

Example log: https://cl-test-grid.appspot.com/blob?key=285051

Note, on lisp-to-c copiler all tests pass. To switch ECL's compiler to bytecode one (ext::install-bytecodes-compiler) should be called.

**Comment by dkochmanski** [comment]
I've made a PR which fixes the bytecmp issue. Basically the problem is that bytecmp does not perform escape analysis, so it always closes over its lexenv.

**Comment by dkochmanski** [comment]
or maybe it is some other issue, I'll investigate it now.

**Comment by dkochmanski** [comment]
I don't know what is exactly the issue, but it has to do with how `voodoo` macro evaluates `(gc :full t)` in bytecmp environment. If we replace a string with `(progn (gc :full t))` then all tests pass, if we put there simple (eval (read-from-string …)) all tests pass etc.

**Comment by dkochmanski** [comment]
so it is most likely some weird bug in eval-with-env function used by the interpreter.

**Comment by dkochmanski** [comment]
this is a weird one. si:gc does not always collect dead data when called from `(eval (read-from-string …))` in case of the bytecmp.

**Comment by dkochmanski** [comment]
from https://github.com/ivmai/bdwgc/blob/master/doc/finalization.md, that would explain why finalizer executed twice solves the issue.

```
This decision is often questioned, particularly since it has an obvious disadvantage. The current implementation finalizes long chains of finalizable objects one per collection. This is hard to avoid, since the first finalizer invoked may store a pointer to the rest of the chain in a global variable, making it accessible again. Or it may mutate the rest of the chain.
```

**Comment by luismbo** [comment]
Fixed via #16.

**Comment by dkochmanski** [comment]
This particular issue is still present (and it stems from using `eval` in voodoo) – I couldn't pinpoint the exact problem. Either way I'd reopen the issue. Thank you for merging the PR.

**Comment by luismbo** [comment]
Oops. 👍
